version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# 1. install the library *and* its doc extras
python:
  install:
    - method: pip
      path: .
      extra_requirements: ["docs"]     # picks the [project.optional-dependencies] above
    - requirements: docs/requirements.txt

# 2. run Sphinx
sphinx:
  configuration: docs/conf.py
